<<<<<<< HEAD
if(!self.define){let e,r={};const i=(i,o)=>(i=new URL(i+".js",o).href,r[i]||new Promise((r=>{if("document"in self){const e=document.createElement("script");e.src=i,e.onload=r,document.head.appendChild(e)}else e=i,importScripts(i),r()})).then((()=>{let e=r[i];if(!e)throw new Error(`Module ${i} didn’t register its module`);return e})));self.define=(o,s)=>{const t=e||("document"in self?document.currentScript.src:"")||location.href;if(r[t])return;let n={};const l=e=>i(e,t),c={module:{uri:t},exports:n,require:l};r[t]=Promise.all(o.map((e=>c[e]||l(e)))).then((e=>(s(...e),n)))}}define(["./workbox-db5fc017"],(function(e){"use strict";e.setCacheNameDetails({prefix:"trial_demo"}),self.addEventListener("message",(e=>{e.data&&"SKIP_WAITING"===e.data.type&&self.skipWaiting()})),e.precacheAndRoute([{url:"/trial_demo/css/chunk-vendors.61d991c8.css",revision:null},{url:"/trial_demo/index.html",revision:"b029e102a45d489572c7c491d14387ff"},{url:"/trial_demo/js/about.576168be.js",revision:null},{url:"/trial_demo/js/app.44adde98.js",revision:null},{url:"/trial_demo/manifest.json",revision:"4d418ae37dbccc7331a0b3a2b8deec9b"},{url:"/trial_demo/robots.txt",revision:"b6216d61c03e6ce0c9aea6ca7808f7ca"}],{})}));
=======
<<<<<<< HEAD
if(!self.define){let e,r={};const i=(i,o)=>(i=new URL(i+".js",o).href,r[i]||new Promise((r=>{if("document"in self){const e=document.createElement("script");e.src=i,e.onload=r,document.head.appendChild(e)}else e=i,importScripts(i),r()})).then((()=>{let e=r[i];if(!e)throw new Error(`Module ${i} didn’t register its module`);return e})));self.define=(o,s)=>{const t=e||("document"in self?document.currentScript.src:"")||location.href;if(r[t])return;let n={};const l=e=>i(e,t),c={module:{uri:t},exports:n,require:l};r[t]=Promise.all(o.map((e=>c[e]||l(e)))).then((e=>(s(...e),n)))}}define(["./workbox-db5fc017"],(function(e){"use strict";e.setCacheNameDetails({prefix:"trial_demo"}),self.addEventListener("message",(e=>{e.data&&"SKIP_WAITING"===e.data.type&&self.skipWaiting()})),e.precacheAndRoute([{url:"/trial_demo/css/chunk-vendors.61d991c8.css",revision:null},{url:"/trial_demo/index.html",revision:"b029e102a45d489572c7c491d14387ff"},{url:"/trial_demo/js/about.576168be.js",revision:null},{url:"/trial_demo/js/app.44adde98.js",revision:null},{url:"/trial_demo/manifest.json",revision:"4d418ae37dbccc7331a0b3a2b8deec9b"},{url:"/trial_demo/robots.txt",revision:"b6216d61c03e6ce0c9aea6ca7808f7ca"}],{})}));
=======
if(!self.define){let e,r={};const i=(i,s)=>(i=new URL(i+".js",s).href,r[i]||new Promise((r=>{if("document"in self){const e=document.createElement("script");e.src=i,e.onload=r,document.head.appendChild(e)}else e=i,importScripts(i),r()})).then((()=>{let e=r[i];if(!e)throw new Error(`Module ${i} didn’t register its module`);return e})));self.define=(s,o)=>{const t=e||("document"in self?document.currentScript.src:"")||location.href;if(r[t])return;let n={};const l=e=>i(e,t),c={module:{uri:t},exports:n,require:l};r[t]=Promise.all(s.map((e=>c[e]||l(e)))).then((e=>(o(...e),n)))}}define(["./workbox-db5fc017"],(function(e){"use strict";e.setCacheNameDetails({prefix:"trial_demo"}),self.addEventListener("message",(e=>{e.data&&"SKIP_WAITING"===e.data.type&&self.skipWaiting()})),e.precacheAndRoute([{url:"/trial_demo/css/chunk-vendors.5487efc8.css",revision:null},{url:"/trial_demo/index.html",revision:"7e9d026da4e246296a35b0762e51e220"},{url:"/trial_demo/js/about.576168be.js",revision:null},{url:"/trial_demo/js/app.ec41973a.js",revision:null},{url:"/trial_demo/js/chunk-vendors.60848398.js",revision:null},{url:"/trial_demo/manifest.json",revision:"4d418ae37dbccc7331a0b3a2b8deec9b"},{url:"/trial_demo/robots.txt",revision:"b6216d61c03e6ce0c9aea6ca7808f7ca"}],{})}));
>>>>>>> 3921b6914384c8ef5b1aa4ede831468fef59a062
>>>>>>> 0cba24619db0435ca9d787a0e4513b3b6218b761
//# sourceMappingURL=service-worker.js.map
